# Form implementation generated from reading ui file 'design/autherization.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_widget_autherization(object):
    def setupUi(self, widget_autherization):
        widget_autherization.setObjectName("widget_autherization")
        widget_autherization.resize(203, 175)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(widget_autherization)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(parent=widget_autherization)
        self.widget.setStyleSheet("background-color: rgb(106, 148, 212);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_username = QtWidgets.QLineEdit(parent=self.widget)
        self.line_username.setText("")
        self.line_username.setObjectName("line_username")
        self.verticalLayout.addWidget(self.line_username)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.line_password = QtWidgets.QLineEdit(parent=self.widget)
        self.line_password.setText("")
        self.line_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.line_password.setObjectName("line_password")
        self.verticalLayout.addWidget(self.line_password)
        self.line_error = QtWidgets.QLabel(parent=self.widget)
        self.line_error.setStyleSheet("color: rgb(255, 0, 0);")
        self.line_error.setText("")
        self.line_error.setObjectName("line_error")
        self.verticalLayout.addWidget(self.line_error)
        self.btn_login = QtWidgets.QPushButton(parent=self.widget)
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout.addWidget(self.btn_login)
        self.reg = QtWidgets.QLabel(parent=self.widget)
        self.reg.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.reg.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.reg.setOpenExternalLinks(True)
        self.reg.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.reg.setObjectName("reg")
        self.verticalLayout.addWidget(self.reg)
        self.verticalLayout_2.addWidget(self.widget)

        self.retranslateUi(widget_autherization)
        QtCore.QMetaObject.connectSlotsByName(widget_autherization)

    def retranslateUi(self, widget_autherization):
        _translate = QtCore.QCoreApplication.translate
        widget_autherization.setWindowTitle(_translate("widget_autherization", "Form"))
        self.label.setText(_translate("widget_autherization", "Логин"))
        self.label_2.setText(_translate("widget_autherization", "Пароль"))
        self.btn_login.setText(_translate("widget_autherization", "Войти"))
        self.reg.setText(_translate("widget_autherization", "<html><head/><body><p><a href=\"http://127.0.0.1:8000/register/\"><span style=\" text-decoration: underline; color:#0000ff;\">Регистрация</span></a></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_autherization = QtWidgets.QWidget()
    ui = Ui_widget_autherization()
    ui.setupUi(widget_autherization)
    widget_autherization.show()
    sys.exit(app.exec())
