# Form implementation generated from reading ui file 'design/profile_update.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UpdateForm(object):
    def setupUi(self, UpdateForm):
        UpdateForm.setObjectName("UpdateForm")
        UpdateForm.resize(310, 254)
        UpdateForm.setStyleSheet("Form#UpdateForm{\n"
"\n"
"background-color: rgb(5, 47, 109);}")
        self.verticalLayout = QtWidgets.QVBoxLayout(UpdateForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=UpdateForm)
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color: rgb(5, 47, 109);}\n"
"")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.widget_profile = QtWidgets.QWidget(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_profile.sizePolicy().hasHeightForWidth())
        self.widget_profile.setSizePolicy(sizePolicy)
        self.widget_profile.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.widget_profile.setStyleSheet("background-color: rgb(106, 148, 212);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.widget_profile.setObjectName("widget_profile")
        self.formLayout = QtWidgets.QFormLayout(self.widget_profile)
        self.formLayout.setObjectName("formLayout")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_profile)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_10)
        self.label_9 = QtWidgets.QLabel(parent=self.widget_profile)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_9)
        self.label_7 = QtWidgets.QLabel(parent=self.widget_profile)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.label_6 = QtWidgets.QLabel(parent=self.widget_profile)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.line_last_name = QtWidgets.QLineEdit(parent=self.widget_profile)
        self.line_last_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.line_last_name.setReadOnly(False)
        self.line_last_name.setObjectName("line_last_name")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_last_name)
        self.line_airport = QtWidgets.QComboBox(parent=self.widget_profile)
        self.line_airport.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.line_airport.setObjectName("line_airport")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_airport)
        self.line_first_name = QtWidgets.QLineEdit(parent=self.widget_profile)
        self.line_first_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.line_first_name.setReadOnly(False)
        self.line_first_name.setObjectName("line_first_name")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_first_name)
        self.line_email = QtWidgets.QLineEdit(parent=self.widget_profile)
        self.line_email.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.line_email.setReadOnly(False)
        self.line_email.setObjectName("line_email")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_email)
        self.btn_update_profile = QtWidgets.QPushButton(parent=self.widget_profile)
        self.btn_update_profile.setObjectName("btn_update_profile")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.btn_update_profile)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.ItemRole.SpanningRole, spacerItem)
        self.verticalLayout_2.addWidget(self.widget_profile)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(UpdateForm)
        QtCore.QMetaObject.connectSlotsByName(UpdateForm)

    def retranslateUi(self, UpdateForm):
        _translate = QtCore.QCoreApplication.translate
        UpdateForm.setWindowTitle(_translate("UpdateForm", "Изменение данных профиля"))
        self.label.setText(_translate("UpdateForm", "Редактирование профиля"))
        self.label_10.setText(_translate("UpdateForm", "Ближайший аэропорт"))
        self.label_9.setText(_translate("UpdateForm", "Почта"))
        self.label_7.setText(_translate("UpdateForm", "Фамилия"))
        self.label_6.setText(_translate("UpdateForm", "Имя"))
        self.btn_update_profile.setText(_translate("UpdateForm", "Изменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UpdateForm = QtWidgets.QWidget()
    ui = Ui_UpdateForm()
    ui.setupUi(UpdateForm)
    UpdateForm.show()
    sys.exit(app.exec())
