# Form implementation generated from reading ui file 'design\ticket.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ticket(object):
    def setupUi(self, ticket):
        ticket.setObjectName("ticket")
        ticket.resize(428, 108)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ticket.sizePolicy().hasHeightForWidth())
        ticket.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(ticket)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(parent=ticket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMaximumSize(QtCore.QSize(123456, 16777215))
        self.widget_3.setStyleSheet("QWidget#widget_3{border-radius:20px;\n"
"border: 1px solid rgb(255, 0, 0)}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.line_ticket_from = QtWidgets.QLineEdit(parent=self.widget)
        self.line_ticket_from.setReadOnly(True)
        self.line_ticket_from.setObjectName("line_ticket_from")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_ticket_from)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.line_ticket_to = QtWidgets.QLineEdit(parent=self.widget)
        self.line_ticket_to.setReadOnly(True)
        self.line_ticket_to.setObjectName("line_ticket_to")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_ticket_to)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.line_ticket_airline = QtWidgets.QLineEdit(parent=self.widget)
        self.line_ticket_airline.setReadOnly(True)
        self.line_ticket_airline.setObjectName("line_ticket_airline")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_ticket_airline)
        self.horizontalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.line_ticket_price = QtWidgets.QLineEdit(parent=self.widget_2)
        self.line_ticket_price.setReadOnly(True)
        self.line_ticket_price.setObjectName("line_ticket_price")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_ticket_price)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget_3)

        self.retranslateUi(ticket)
        QtCore.QMetaObject.connectSlotsByName(ticket)

    def retranslateUi(self, ticket):
        _translate = QtCore.QCoreApplication.translate
        ticket.setWindowTitle(_translate("ticket", "Form"))
        self.label_2.setText(_translate("ticket", "Откуда"))
        self.label_3.setText(_translate("ticket", "Куда"))
        self.label_5.setText(_translate("ticket", "Компания"))
        self.label_4.setText(_translate("ticket", "Цена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ticket = QtWidgets.QWidget()
    ui = Ui_ticket()
    ui.setupUi(ticket)
    ticket.show()
    sys.exit(app.exec())
