# Form implementation generated from reading ui file 'design/who.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WhoWidget(object):
    def setupUi(self, WhoWidget):
        WhoWidget.setObjectName("WhoWidget")
        WhoWidget.resize(162, 178)
        self.verticalLayout = QtWidgets.QVBoxLayout(WhoWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(parent=WhoWidget)
        self.widget_3.setStyleSheet("QWidget#widget_3{\n"
"background-color: rgb(5, 47, 109);\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(parent=self.widget_3)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.line_ch = QtWidgets.QLineEdit(parent=self.widget)
        self.line_ch.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.line_ch.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.line_ch.setText("")
        self.line_ch.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.line_ch.setObjectName("line_ch")
        self.gridLayout.addWidget(self.line_ch, 2, 2, 2, 1)
        self.line_inf = QtWidgets.QLineEdit(parent=self.widget)
        self.line_inf.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.line_inf.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.line_inf.setText("")
        self.line_inf.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.line_inf.setObjectName("line_inf")
        self.gridLayout.addWidget(self.line_inf, 4, 2, 2, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.line_ad = QtWidgets.QLineEdit(parent=self.widget)
        self.line_ad.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.line_ad.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.line_ad.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.line_ad.setPlaceholderText("")
        self.line_ad.setObjectName("line_ad")
        self.gridLayout.addWidget(self.line_ad, 0, 2, 2, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.error = QtWidgets.QLabel(parent=self.widget_2)
        self.error.setStyleSheet("color: rgb(255, 0, 0);")
        self.error.setText("")
        self.error.setObjectName("error")
        self.verticalLayout_2.addWidget(self.error)
        self.btn_ok = QtWidgets.QPushButton(parent=self.widget_2)
        self.btn_ok.setStyleSheet("background-color: rgb(5, 47, 109);\n"
"color: rgb(255, 255, 255);")
        self.btn_ok.setObjectName("btn_ok")
        self.verticalLayout_2.addWidget(self.btn_ok)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget_3)

        self.retranslateUi(WhoWidget)
        QtCore.QMetaObject.connectSlotsByName(WhoWidget)

    def retranslateUi(self, WhoWidget):
        _translate = QtCore.QCoreApplication.translate
        WhoWidget.setWindowTitle(_translate("WhoWidget", "Пассажиры"))
        self.line_ch.setPlaceholderText(_translate("WhoWidget", "0"))
        self.line_inf.setPlaceholderText(_translate("WhoWidget", "0"))
        self.label_3.setText(_translate("WhoWidget", "Младенцы"))
        self.label.setText(_translate("WhoWidget", "Взрослые"))
        self.label_4.setText(_translate("WhoWidget", "от 12 лет"))
        self.line_ad.setText(_translate("WhoWidget", "1"))
        self.label_2.setText(_translate("WhoWidget", "Дети"))
        self.label_5.setText(_translate("WhoWidget", "от 3 лет до 12 лет"))
        self.label_6.setText(_translate("WhoWidget", "до 3 лет, без места"))
        self.btn_ok.setText(_translate("WhoWidget", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WhoWidget = QtWidgets.QWidget()
    ui = Ui_WhoWidget()
    ui.setupUi(WhoWidget)
    WhoWidget.show()
    sys.exit(app.exec())
