# Generated by Django 4.2.7 on 2023-12-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ad',
            field=models.IntegerField(null=True, verbose_name='Кол-во взрослых'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ch',
            field=models.IntegerField(null=True, verbose_name='Кол-во детей'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='inf',
            field=models.IntegerField(null=True, verbose_name='Кол-во младенцев'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(verbose_name='Оплачен'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket',
            field=models.JSONField(null=True, verbose_name='Билет'),
        ),
    ]
