# Generated by Django 4.2.7 on 2023-12-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ticket_price_alter_ticket_ad_alter_ticket_ch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='num_stops',
            field=models.IntegerField(null=True, verbose_name='Кол-во пересадок'),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_from', models.CharField(max_length=30, verbose_name='Откуда')),
                ('air_to', models.CharField(max_length=30, verbose_name='Куда')),
                ('air_line', models.CharField(max_length=30, verbose_name='Авиакомпания')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена')),
                ('tick', models.ManyToManyField(to='main.ticket', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Полет',
                'verbose_name_plural': 'Полеты',
            },
        ),
    ]
