# Generated by Django 4.2.7 on 2023-12-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='tick',
        ),
        migrations.AddField(
            model_name='ticket',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='flights', to='main.flight', verbose_name='Полет'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
    ]
