# Generated by Django 4.2.7 on 2023-12-14 18:25

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0004_remove_flight_tick_ticket_flights_alter_ticket_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='fls', to='main.flight', verbose_name='Полет'),
        ),
    ]
