# Generated by Django 4.2.7 on 2023-12-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_alter_ticket_flights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='flights',
            field=models.ManyToManyField(blank=True, to='main.flight', verbose_name='Полет'),
        ),
    ]
