# Generated by Django 4.2.7 on 2023-12-16 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ticket_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile', verbose_name='Профиль'),
        ),
    ]
