# Generated by Django 4.2.7 on 2023-12-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_ticket_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Код')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='air_from',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='air_to',
        ),
        migrations.AddField(
            model_name='flight',
            name='from_air',
            field=models.ManyToManyField(blank=True, related_name='from_air', to='main.airport', verbose_name='Из'),
        ),
        migrations.AddField(
            model_name='flight',
            name='to_air',
            field=models.ManyToManyField(blank=True, related_name='to_air', to='main.airport', verbose_name='В'),
        ),
    ]
