# Generated by Django 4.2.7 on 2023-12-17 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_airport_remove_flight_air_from_remove_flight_air_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='from_air',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='to_air',
        ),
        migrations.AddField(
            model_name='flight',
            name='from_air',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_air', to='main.airport', verbose_name='Из'),
        ),
        migrations.AddField(
            model_name='flight',
            name='to_air',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_air', to='main.airport', verbose_name='В'),
        ),
    ]
