# Generated by Django 4.2.7 on 2023-12-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_flight_from_air_remove_flight_to_air_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(max_length=60, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
    ]
