# Generated by Django 4.2.7 on 2023-12-17 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_airport_code_alter_airport_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='from_air',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='to_air',
        ),
        migrations.AddField(
            model_name='flight',
            name='from_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_airport', to='main.airport', verbose_name='Из'),
        ),
        migrations.AddField(
            model_name='flight',
            name='to_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_airport', to='main.airport', verbose_name='В'),
        ),
    ]
