# Generated by Django 4.2.7 on 2023-12-17 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_flight_from_air_remove_flight_to_air_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='air_line',
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='main.airport', verbose_name='Из'),
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.airline', verbose_name='Авиакомпания'),
        ),
    ]
