# Generated by Django 4.2.7 on 2023-12-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_airline_remove_flight_air_line_alter_airport_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=30, null=True, verbose_name='Ближайший аэропорт'),
        ),
    ]
